Repository nowsprinting/test-helper.ui, pull requests merged in 2023-11, with the labels that each got.

#51 Add take screenshots option
  .github/workflows/test.yml
  README.md
  Runtime/Monkey.cs
  Runtime/MonkeyConfig.cs
  Tests/Runtime/MonkeyTest.cs
  package.json
Labels: enhancement

#55 Mod emoji in releases
  .github/release-drafter.yml
Labels: chore

#50 Add a text input operator
  Runtime/InteractiveComponent.cs
  Runtime/Monkey.cs
  Runtime/MonkeyConfig.cs
  Runtime/Operators/TextInputOperator.cs
  Runtime/Operators/TextInputOperator.cs.meta
  Runtime/Random/CharactersKind.cs
  Runtime/Random/CharactersKind.cs.meta
  Runtime/Random/IRandomString.cs
  Runtime/Random/IRandomString.cs.meta
  Runtime/Random/RandomStringImpl.cs
  Runtime/Random/RandomStringImpl.cs.meta
  Runtime/Random/RandomStringParameters.cs
  Runtime/Random/RandomStringParameters.cs.meta
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/Operators/TextInputOperatorTest.cs
  Tests/Runtime/Operators/TextInputOperatorTest.cs.meta
  Tests/Runtime/Random.meta
  Tests/Runtime/Random/RandomStringTest.cs
  Tests/Runtime/Random/RandomStringTest.cs.meta
  Tests/Runtime/TestDoubles/StubRandomString.cs
  Tests/Runtime/TestDoubles/StubRandomString.cs.meta
  Tests/Scenes/Operators.unity
Labels: enhancement

#56 Replace the random implementation with TestHelper.Random package
  Runtime/Monkey.cs
  Runtime/MonkeyConfig.cs
  Runtime/Random/IRandom.cs
  Runtime/Random/RandomImpl.cs
  Runtime/TestHelper.Monkey.asmdef
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/TestDoubles/StubRandom.cs
  Tests/Runtime/TestHelper.Monkey.Tests.asmdef
  package.json
Labels: chore

#57 Fix conflict Random
  Runtime/MonkeyConfig.cs
  Runtime/Random/IRandom.cs
  Runtime/Random/IRandom.cs.meta
  Runtime/Random/RandomImpl.cs
  Runtime/Random/RandomImpl.cs.meta
  Runtime/Random/RandomStringImpl.cs
  Tests/Runtime/Random/RandomStringTest.cs
Labels: bug

#53 Show hints for interactive components on SceneView and GameView (only if Gizmoz enabled)
  Editor/ContextMenu.meta
  Editor/ContextMenu/HintComponentMenu.cs
  Editor/ContextMenu/HintComponentMenu.cs.meta
  Editor/Localization/ja.po
  Editor/TestHelper.Monkey.Editor.asmdef
  Editor/UI/Hints.meta
  Editor/UI/Hints/InteractiveComponentHintEditor.cs
  Editor/UI/Hints/InteractiveComponentHintEditor.cs.meta
  Editor/UI/Hints/InteractiveComponentHintGizmoDrawer.cs
  Editor/UI/Hints/InteractiveComponentHintGizmoDrawer.cs.meta
  Runtime/CameraSelector.cs
  Runtime/CameraSelector.cs.meta
  Runtime/Hints.meta
  Runtime/Hints/InteractiveComponentHint.cs
  Runtime/Hints/InteractiveComponentHint.cs.meta
  Runtime/Hints/InteractiveComponentHintPosition.cs
  Runtime/Hints/InteractiveComponentHintPosition.cs.meta
  Runtime/InteractiveComponent.cs
  Runtime/ScreenPointStrategies/GameObjectPosition.cs
  Tests/Runtime/Hints.meta
  Tests/Runtime/Hints/InteractiveComponentHintPositionTest.cs
  Tests/Runtime/Hints/InteractiveComponentHintPositionTest.cs.meta
  Tests/Scenes/Annotations.unity
  Tests/Scenes/Hints.unity
  Tests/Scenes/Hints.unity.meta
  Tests/Scenes/HintsSettings.lighting
  Tests/Scenes/HintsSettings.lighting.meta
Labels: enhancement

#59 Fix screenshot options
  README.md
  Runtime/Monkey.cs
  Runtime/MonkeyConfig.cs
  Runtime/ScreenshotOptions.cs
  Runtime/ScreenshotOptions.cs.meta
  Tests/Runtime/MonkeyTest.cs
Labels: bug

#58 Add InputFieldAnnotation
  Annotations/Enums.meta
  Annotations/Enums/CharactersKind.cs
  Annotations/Enums/CharactersKind.cs.meta
  Annotations/InputFieldAnnotation.cs
  Annotations/InputFieldAnnotation.cs.meta
  Editor/Localization/ja.po
  Editor/TestHelper.Monkey.Editor.asmdef
  Editor/UI/Annotations/InputFieldAnnotationEditor.cs
  Editor/UI/Annotations/InputFieldAnnotationEditor.cs.meta
  Editor/UI/Annotations/ScreenOffsetAnnotationEditor.cs
  Editor/UI/Annotations/ScreenPositionAnnotationEditor.cs
  Editor/UI/Annotations/WorldOffsetAnnotationEditor.cs
  Editor/UI/Annotations/WorldPositionAnnotationEditor.cs
  README.md
  Runtime/Operators/TextInputOperator.cs
  Runtime/Random/CharactersKind.cs.meta
  Runtime/Random/RandomStringImpl.cs
  Runtime/Random/RandomStringParameters.cs
  Tests/Runtime/Annotations/InputFieldAnnotationTest.cs
  Tests/Runtime/Annotations/InputFieldAnnotationTest.cs.meta
  Tests/Runtime/Annotations/PositionAnnotationTest.cs
  Tests/Runtime/Random/RandomStringTest.cs
  Tests/Runtime/TestDoubles/SpyInputFieldValidator.cs
  Tests/Runtime/TestDoubles/SpyInputFieldValidator.cs.meta
  Tests/Scenes/InputFIelds.unity
  Tests/Scenes/InputFIelds.unity.meta
  Tests/Scenes/PositionAnnotations.unity
  Tests/Scenes/PositionAnnotations.unity.meta
Labels: enhancement

#60 Update test-helper.random package to v0.2.0
  Tests/Runtime/TestDoubles/StubRandom.cs
  package.json
Labels: chore

#66 Make Do not run tests on public fork
  .github/workflows/test.yml
Labels: chore

#67 Make do not run release workflows on public fork
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: chore

#69 Fix skip notifications
  .github/workflows/actionlint.yml
  .github/workflows/metacheck.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: chore

#70 Add comments and description to tests about stereo rendering settings
  Tests/Runtime/MonkeyTest.cs
Labels: chore

#71 Fix how to development
  README.md
Labels: chore
