Repository nowsprinting/test-helper.ui, pull requests merged in 2023-10, with the labels that each got.

#40 Fix MissingReferenceException
  Runtime/Operators/TouchAndHoldOperator.cs
  Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
  Tests/Runtime/TestDoubles/StubDestroyingItselfWhenPointerDown.cs
  Tests/Runtime/TestDoubles/StubDestroyingItselfWhenPointerDown.cs.meta
  Tests/Scenes/Operators.unity
Labels: bug

#42 Replace Task to UniTask
  Runtime/InteractiveComponent.cs
  Runtime/Operators/TouchAndHoldOperator.cs
Labels: chore

#44 Remove actions/setup-node from test workflow
  .github/workflows/test.yml
Labels: chore

#46 Refactor tests
  README.md
  Tests/Runtime/InteractiveComponentCollectorTest.cs
  Tests/Runtime/InteractiveComponentTest.cs
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/Operators/ClickOperatorTest.cs
  Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
  Tests/Runtime/TestDoubles/StubDestroyingItselfWhenPointerDown.cs
Labels: chore

#48 Mod screen resolution specify for each class in tests
  Tests/Runtime/AssemblyInfo.cs
  Tests/Runtime/AssemblyInfo.cs.meta
  Tests/Runtime/InteractiveComponentCollectorTest.cs
  Tests/Runtime/InteractiveComponentTest.cs
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/Operators/ClickOperatorTest.cs
  Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
Labels: chore

#49 Add show Gizmos option
  README.md
  Runtime/Monkey.cs
  Runtime/MonkeyConfig.cs
  Runtime/TestHelper.Monkey.asmdef
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/TestHelper.Monkey.Tests.asmdef
  package.json
Labels: enhancement
