Repository nowsprinting/test-helper.ui, pull requests merged in 2024-03, with the labels that each got.

#64 Introduce screenshot file name strategies
  Runtime/Monkey.cs
  Runtime/ScreenshotFilenameStrategies.meta
  Runtime/ScreenshotFilenameStrategies/AbstractPrefixAndUniqueIDStrategy.cs
  Runtime/ScreenshotFilenameStrategies/AbstractPrefixAndUniqueIDStrategy.cs.meta
  Runtime/ScreenshotFilenameStrategies/CounterBasedStrategy.cs
  Runtime/ScreenshotFilenameStrategies/CounterBasedStrategy.cs.meta
  Runtime/ScreenshotFilenameStrategies/IScreenshotFilenameStrategy.cs
  Runtime/ScreenshotFilenameStrategies/IScreenshotFilenameStrategy.cs.meta
  Runtime/ScreenshotOptions.cs
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/ScreenshotFilenameStrategies.meta
  Tests/Runtime/ScreenshotFilenameStrategies/CounterBasedStrategyTest.cs
  Tests/Runtime/ScreenshotFilenameStrategies/CounterBasedStrategyTest.cs.meta
  Tests/Runtime/TestDoubles/StubScreenshotFilenameStrategy.cs
  Tests/Runtime/TestDoubles/StubScreenshotFilenameStrategy.cs.meta
Labels: enhancement

#83 [TEMPORARY] Add specify version number for com.unity packages
  .github/workflows/test.yml
  Makefile
Labels: chore

#84 Fix minor recommend
  Runtime/ScreenshotOptions.cs
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/ScreenshotFilenameStrategies/CounterBasedStrategyTest.cs
Labels: chore

#86 Revert "[TEMPORARY] Add specify version number for com.unity packages"
  .github/workflows/test.yml
  Makefile
Labels: chore

#88 Add specify directories for publishing in the `files` field (Fix "Broken v0.6.0 in the openupm.com")
  package.json
Labels: chore

#90 Add demo app into Samples
  .github/release-pr-template.md
  Samples~/TestHelper.Monkey.Demo.meta
  Samples~/TestHelper.Monkey.Demo/Scenes.meta
  Samples~/TestHelper.Monkey.Demo/Scenes/Demo.unity
  Samples~/TestHelper.Monkey.Demo/Scenes/Demo.unity.meta
  Samples~/TestHelper.Monkey.Demo/Scripts.meta
  Samples~/TestHelper.Monkey.Demo/Scripts/Runtime.meta
  Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/MonkeyController.cs
  Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/MonkeyController.cs.meta
  Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/TestHelper.Monkey.Demo.asmdef
  Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/TestHelper.Monkey.Demo.asmdef.meta
  Samples~/TestHelper.Monkey.Demo/Tests.meta
  Samples~/TestHelper.Monkey.Demo/Tests/Runtime.meta
  Samples~/TestHelper.Monkey.Demo/Tests/Runtime/MonkeyTest.cs
  Samples~/TestHelper.Monkey.Demo/Tests/Runtime/MonkeyTest.cs.meta
  Samples~/TestHelper.Monkey.Demo/Tests/Runtime/TestHelper.Monkey.Demo.Tests.asmdef
  Samples~/TestHelper.Monkey.Demo/Tests/Runtime/TestHelper.Monkey.Demo.Tests.asmdef.meta
  package.json
Labels: enhancement

#92 Fix README.md
  README.md
Labels: chore

#91 Fix take screenshots problem when running not on test runner
  Runtime/ScreenshotFilenameStrategies/AbstractPrefixAndUniqueIDStrategy.cs
  Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/MonkeyController.cs
  Samples~/TestHelper.Monkey.Demo/Scripts/Runtime/TestHelper.Monkey.Demo.asmdef
Labels: bug

#93 Optimize tests
  Tests/Runtime/Annotations/InputFieldAnnotationTest.cs
  Tests/Runtime/Annotations/PositionAnnotationTest.cs
  Tests/Runtime/AssemblyInfo.cs
  Tests/Runtime/AssemblyInfo.cs.meta
  Tests/Runtime/Hints/InteractiveComponentHintPositionTest.cs
  Tests/Runtime/InteractiveComponentCollectorTest.cs
  Tests/Runtime/InteractiveComponentTest.cs
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/Operators/ClickOperatorTest.cs
  Tests/Runtime/Operators/TextInputOperatorTest.cs
  Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
  Tests/Scenes/MonkeyUiScreenSpaceCamera.unity
  Tests/Scenes/MonkeyUiScreenSpaceOverlay.unity
  Tests/Scenes/MonkeyUiWorldSpace.unity
Labels: chore

#96 Add GameObjectFinder
  Editor/ContextMenu/HintComponentMenu.cs
  Editor/UI/Hints/InteractiveComponentHintEditor.cs
  Editor/UI/Hints/InteractiveComponentHintGizmoDrawer.cs
  README.md
  Runtime/CameraSelector.cs
  Runtime/Extensions.meta
  Runtime/Extensions/ComponentExtensions.cs
  Runtime/Extensions/ComponentExtensions.cs.meta
  Runtime/Extensions/GameObjectExtensions.cs
  Runtime/Extensions/GameObjectExtensions.cs.meta
  Runtime/Extensions/TransformExtensions.cs
  Runtime/Extensions/TransformExtensions.cs.meta
  Runtime/GameObjectFinder.cs
  Runtime/GameObjectFinder.cs.meta
  Runtime/Hints/InteractiveComponentHint.cs
  Runtime/Hints/InteractiveComponentHintPosition.cs
  Runtime/InteractiveComponent.cs
  Runtime/InteractiveComponentCollector.cs
  Runtime/Monkey.cs
  Runtime/Operators/ClickOperator.cs
  Runtime/Operators/TouchAndHoldOperator.cs
  Runtime/ScreenPointStrategies/GameObjectPosition.cs
  Tests/Runtime/Annotations/PositionAnnotationTest.cs
  Tests/Runtime/Extensions.meta
  Tests/Runtime/Extensions/TransformExtensionsTest.cs
  Tests/Runtime/Extensions/TransformExtensionsTest.cs.meta
  Tests/Runtime/GameObjectFinderTest.cs
  Tests/Runtime/GameObjectFinderTest.cs.meta
  Tests/Runtime/InteractiveComponentCollectorTest.cs
  Tests/Runtime/InteractiveComponentTest.cs
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/Operators/ClickOperatorTest.cs
  Tests/Runtime/Operators/TextInputOperatorTest.cs
  Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
  Tests/Scenes/GameObjectFinder2D.unity
  Tests/Scenes/GameObjectFinder2D.unity.meta
  Tests/Scenes/GameObjectFinder3D.unity
  Tests/Scenes/GameObjectFinder3D.unity.meta
  Tests/Scenes/GameObjectFinderUI.unity
  Tests/Scenes/GameObjectFinderUI.unity.meta
Labels: enhancement

#97 Add command line argument to specify screenshot save directory
  .github/workflows/test.yml
  Makefile
  README.md
  Runtime/ScreenshotOptions.cs
  Tests/Runtime/MonkeyTest.cs
  package.json
Labels: enhancement

#98 Fix case in test scene name
  Tests/Scenes/InputFields.unity
  Tests/Scenes/InputFields.unity.meta
Labels: chore

#99 Fix misspelling
  README.md
  Runtime/Extensions/TransformExtensions.cs
  Runtime/GameObjectFinder.cs
  Tests/Runtime/Extensions/TransformExtensionsTest.cs
Labels: bug

#100 Refactor set default screenshot save directory to null
  Runtime/ScreenshotOptions.cs
Labels: chore

#103 Refactor InteractiveComponent
  Runtime/GameObjectFinder.cs
  Runtime/Hints/InteractiveComponentHint.cs
  Runtime/InteractiveComponent.cs
  Runtime/InteractiveComponentCollector.cs
  Runtime/Monkey.cs
  Tests/Runtime/Annotations/PositionAnnotationTest.cs
  Tests/Runtime/InteractiveComponentCollectorTest.cs
  Tests/Runtime/InteractiveComponentTest.cs
  Tests/Runtime/MonkeyTest.cs
  Tests/Runtime/Operators/ClickOperatorTest.cs
  Tests/Runtime/Operators/TextInputOperatorTest.cs
  Tests/Runtime/Operators/TouchAndHoldOperatorTest.cs
Labels: chore

#105 Fix namespace in Editor
  Editor/ContextMenu/HintComponentMenu.cs
  Editor/UI/Hints/InteractiveComponentHintEditor.cs
  Editor/UI/Hints/InteractiveComponentHintGizmoDrawer.cs
Labels: bug

#107 Add reachable and interactable examine strategies into MonkeyConfig
  Runtime/DefaultStrategies/DefaultGameObjectInteractableStrategy.cs
  Runtime/DefaultStrategies/DefaultGameObjectInteractableStrategy.cs.meta
  Runtime/DefaultStrategies/DefaultReachableStrategy.cs
  Runtime/GameObjectFinder.cs
  Runtime/InteractiveComponent.cs
  Runtime/InteractiveComponentCollector.cs
  Runtime/Monkey.cs
  Runtime/MonkeyConfig.cs
Labels: enhancement

#111 Add CreateInteractableComponent(MonoBehaviour) static method
  Runtime/InteractiveComponent.cs
  Runtime/InteractiveComponentCollector.cs
  Samples~/uGUI Demo/Tests/Runtime/ScenarioTest.cs
  Tests/Runtime/InteractiveComponentTest.cs
  Tests/Runtime/MonkeyTest.cs
Labels: enhancement

#113 Add comments
  Tests/Runtime/GameObjectFinderTest.cs
Labels: chore

#114 Mod CreateInteractableComponent throws ArgumentException if component is not interactable
  Runtime/InteractiveComponent.cs
  Tests/Runtime/InteractiveComponentTest.cs
Labels: chore
